apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: pvm5ht5ua-go 
  janus-idp.io/tekton: pvm5ht5ua-go
  backstage.io/kubernetes-id: pvm5ht5ua-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pvm5ht5ua-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml